#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script to replace Cyrillic comments with English
Usage: python replace_cyrillic.py
"""

import os
import re
from pathlib import Path

# Translation dictionary for common Ukrainian comments
TRANSLATIONS = {
    # Common patterns
    'Імпортуємо': 'Import',
    'імпортуємо': 'import',
    'Ініціалізація': 'Initialize',
    'ініціалізація': 'initialize',
    'Модуль': 'Module',
    'модуль': 'module',
    'Конфігурація': 'Configuration',
    'конфігурація': 'configuration',
    'за замовчуванням': 'default',
    'За замовчуванням': 'Default',
    'Глобальні змінні': 'Global variables',
    'глобальні змінні': 'global variables',
    'для взаємодії між модулями': 'for interaction between modules',
    'Встановлюємо': 'Set',
    'встановлюємо': 'set',
    'початкову': 'initial',
    'Початкову': 'Initial',
    'Автоматично': 'Automatically',
    'автоматично': 'automatically',
    'змінюємо': 'change',
    'Змінюємо': 'Change',
    'висоту': 'height',
    'Висоту': 'Height',
    'при введенні тексту': 'on text input',
    'Також': 'Also',
    'також': 'also',
    'при завантаженні сторінки': 'on page load',
    'Максимальна висота': 'Maximum height',
    'максимальна висота': 'maximum height',
    'Якщо': 'If',
    'якщо': 'if',
    'вже є': 'already exists',
    'Вже є': 'Already exists',
    'оновлюємо': 'update',
    'Оновлюємо': 'Update',
    'немає': "doesn't exist",
    'Немає': "Doesn't exist",
    'вставляємо': 'insert',
    'Вставляємо': 'Insert',
    'новий': 'new',
    'Новий': 'New',
    'кастомною': 'custom',
    'Кастомною': 'Custom',
    'Після збірки': 'After build',
    'після збірки': 'after build',
    'виправляємо': 'fix',
    'Виправляємо': 'Fix',
    'шляхи': 'paths',
    'Шляхи': 'Paths',
    'Додаємо': 'Add',
    'додаємо': 'add',
    'base path': 'base path',
    'до відносних': 'to relative',
    'Пропускаємо': 'Skip',
    'пропускаємо': 'skip',
    'які вже мають': 'that already have',
    'Створюємо': 'Create',
    'створюємо': 'create',
    'файл': 'file',
    'Файл': 'File',
    'для': 'for',
    'Для': 'For',
    'Перевіряємо': 'Check',
    'перевіряємо': 'check',
    'тільки': 'only',
    'Тільки': 'Only',
    'на десктопі': 'on desktop',
    'ширина': 'width',
    'Ширина': 'Width',
    'при завантаженні': 'on load',
    'При завантаженні': 'On load',
    'при resize': 'on resize',
    'При resize': 'On resize',
    'при scroll': 'on scroll',
    'При scroll': 'On scroll',
    'Не': 'Not',
    'не': 'not',
    'відкрите': 'open',
    'Відкрите': 'Open',
    'меню': 'menu',
    'Меню': 'Menu',
    'Плавна прокрутка': 'Smooth scroll',
    'плавна прокрутка': 'smooth scroll',
    'навігації': 'navigation',
    'Навігації': 'Navigation',
    'після': 'after',
    'Після': 'After',
    'перед': 'before',
    'Перед': 'Before',
    'має бути': 'must be',
    'Має бути': 'Must be',
    'може оновити': 'can update',
    'Може оновити': 'Can update',
    'існуючу': 'existing',
    'Існуючу': 'Existing',
    'потрібно': 'needed',
    'Потрібно': 'Needed',
    'Розкоментуйте': 'Uncomment',
    'розкоментуйте': 'uncomment',
    'динамічно': 'dynamically',
    'Динамічно': 'Dynamically',
    'секції': 'section',
    'Секції': 'Section',
    'секція': 'section',
    'Секція': 'Section',
    'поточній сторінці': 'current page',
    'Поточній сторінці': 'Current page',
    'ефекту': 'effect',
    'Ефекту': 'Effect',
    'скролу': 'scroll',
    'Скролу': 'Scroll',
    'затемнення': 'darkening',
    'Затемнення': 'Darkening',
    'при скролі': 'on scroll',
    'При скролі': 'On scroll',
    'Розраховуємо': 'Calculate',
    'розраховуємо': 'calculate',
    'прогрес': 'progress',
    'Прогрес': 'Progress',
    'видима': 'visible',
    'Видима': 'Visible',
    'на екрані': 'on screen',
    'На екрані': 'On screen',
    'повністю': 'completely',
    'Повністю': 'Completely',
    'прокручена': 'scrolled',
    'Прокручена': 'Scrolled',
    'вгору': 'up',
    'Вгору': 'Up',
    'Динамічно': 'Dynamically',
    'динамічно': 'dynamically',
    'змінюємо': 'change',
    'прозорість': 'opacity',
    'Прозорість': 'Opacity',
    'Додаємо': 'Add',
    'клас': 'class',
    'Клас': 'Class',
    'плавного': 'smooth',
    'Плавного': 'Smooth',
    'переходу': 'transition',
    'Переходу': 'Transition',
    'Анімація': 'Animation',
    'анімація': 'animation',
    'елементів': 'elements',
    'Елементів': 'Elements',
    'при завантаженні': 'on load',
    'Спочатку': 'First',
    'спочатку': 'first',
    'ховаємо': 'hide',
    'Ховаємо': 'Hide',
    'зліва': 'from left',
    'Зліва': 'From left',
    'зверху': 'from top',
    'Зверху': 'From top',
    'справа': 'from right',
    'Справа': 'From right',
    'по черзі': 'one by one',
    'По черзі': 'One by one',
    'при hover': 'on hover',
    'При hover': 'On hover',
    'каруселі': 'carousel',
    'Каруселі': 'Carousel',
    'проектів': 'projects',
    'Проектів': 'Projects',
    'infinite loop': 'infinite loop',
    'Зберігаємо': 'Store',
    'зберігаємо': 'store',
    'посилання': 'reference',
    'Посилання': 'Reference',
    'на всі': 'on all',
    'На всі': 'On all',
    'створені': 'created',
    'Створені': 'Created',
    'для можливості': 'for ability',
    'Для можливості': 'For ability',
    'очищення': 'cleanup',
    'Очищення': 'Cleanup',
    'Очищення всіх': 'Cleanup all',
    'очищення всіх': 'cleanup all',
    'видалення': 'removal',
    'Видалення': 'Removal',
    'слухачів': 'listeners',
    'Слухачів': 'Listeners',
    'подій': 'events',
    'Подій': 'Events',
    'Корисно': 'Useful',
    'корисно': 'useful',
    'при динамічному': 'on dynamic',
    'При динамічному': 'On dynamic',
    'оновленні': 'update',
    'Оновленні': 'Update',
    'Отримати': 'Get',
    'отримати': 'get',
    'всі': 'all',
    'Всі': 'All',
    'екземпляри': 'instances',
    'Екземпляри': 'Instances',
    'для програмного': 'for programmatic',
    'Для програмного': 'For programmatic',
    'керування': 'control',
    'Керування': 'Control',
    'Компонент': 'Component',
    'компонент': 'component',
    'перевикористовуваний': 'reusable',
    'Перевикористовуваний': 'Reusable',
    'клас': 'class',
    'Клас': 'Class',
    'для роботи': 'for working',
    'Для роботи': 'For working',
    'Чи використовувати': 'Whether to use',
    'чи використовувати': 'whether to use',
    'безкінечний': 'infinite',
    'Безкінечний': 'Infinite',
    'цикл': 'cycle',
    'Цикл': 'Cycle',
    'Тривалість': 'Duration',
    'тривалість': 'duration',
    'анімації': 'animation',
    'Анімації': 'Animation',
    'переходу': 'transition',
    'Переходу': 'Transition',
    'в мс': 'in ms',
    'В мс': 'In ms',
    'Поріг': 'Threshold',
    'поріг': 'threshold',
    'для свайпу': 'for swipe',
    'Для свайпу': 'For swipe',
    'на мобільних': 'on mobile',
    'На мобільних': 'On mobile',
    'пристроях': 'devices',
    'Пристроях': 'Devices',
    'Селектор': 'Selector',
    'селектор': 'selector',
    'для кнопки': 'for button',
    'Для кнопки': 'For button',
    'Попереднє': 'Previous',
    'попереднє': 'previous',
    'Наступне': 'Next',
    'наступне': 'next',
    'для треку': 'for track',
    'Для треку': 'For track',
    'Обробники': 'Handlers',
    'обробники': 'handlers',
    'подій': 'events',
    'для видалення': 'for removal',
    'Для видалення': 'For removal',
    'Встановлюємо опції': 'Set options',
    'встановлюємо опції': 'set options',
    'Знаходимо': 'Find',
    'знаходимо': 'find',
    'елементи': 'elements',
    'Елементи': 'Elements',
    'Отримуємо': 'Get',
    'отримуємо': 'get',
    'слайди': 'slides',
    'Слайди': 'Slides',
    'Ініціалізуємо': 'Initialize',
    'ініціалізуємо': 'initialize',
    'Приховуємо': 'Hide',
    'приховуємо': 'hide',
    'кнопки': 'buttons',
    'Кнопки': 'Buttons',
    'є тільки': 'only has',
    'Є тільки': 'Only has',
    'слайд': 'slide',
    'Слайд': 'Slide',
    'не додаємо': "don't add",
    'Не додаємо': "Don't add",
    'Налаштовуємо': 'Setup',
    'налаштовуємо': 'setup',
    'Встановлюємо початкову': 'Set initial',
    'встановлюємо початкову': 'set initial',
    'позицію': 'position',
    'Позицію': 'Position',
    'Додаємо': 'Add',
    'слухачі': 'listeners',
    'Слухачі': 'Listeners',
    'Оновлюємо': 'Update',
    'оновлюємо': 'update',
    'при зміні': 'on change',
    'При зміні': 'On change',
    'розміру': 'size',
    'Розміру': 'Size',
    'вікна': 'window',
    'Вікна': 'Window',
    'Захист': 'Protection',
    'захист': 'protection',
    'від подвійного': 'from double',
    'Від подвійного': 'From double',
    'навішування': 'binding',
    'Навішування': 'Binding',
    'Закриваємо': 'Close',
    'закриваємо': 'close',
    'всі інші': 'all other',
    'Всі інші': 'All other',
    'Перемикаємо': 'Toggle',
    'перемикаємо': 'toggle',
    'поточний': 'current',
    'Поточний': 'Current',
    'Визначення': 'Determine',
    'визначення': 'determine',
    'поточної': 'current',
    'Поточної': 'Current',
    'сторінки': 'page',
    'Сторінки': 'Page',
    'за URL': 'by URL',
    'За URL': 'By URL',
    'Модуль для': 'Module for',
    'модуль для': 'module for',
    'динамічних': 'dynamic',
    'Динамічних': 'Dynamic',
    'ефектів': 'effects',
    'Ефектів': 'Effects',
    'фону': 'background',
    'Фону': 'Background',
    'анімованого': 'animated',
    'Анімованого': 'Animated',
    'градієнта': 'gradient',
    'Градієнта': 'Gradient',
    'overlay': 'overlay',
    'Працює': 'Works',
    'працює': 'works',
    'тільки на': 'only on',
    'Тільки на': 'Only on',
    'головній': 'main',
    'Головній': 'Main',
    'не на': 'not on',
    'Не на': 'Not on',
    'підсторінках': 'subpages',
    'Підсторінках': 'Subpages',
    'Функція': 'Function',
    'функція': 'function',
    'збережена': 'saved',
    'Збережена': 'Saved',
    'майбутнього': 'future',
    'Майбутнього': 'Future',
    'використання': 'use',
    'Використання': 'Use',
    'інших': 'other',
    'Інших': 'Other',
    'Не використовуємо': "Don't use",
    'не використовуємо': "don't use",
    'анімацію': 'animation',
    'Анімацію': 'Animation',
    'частинки': 'particles',
    'Частинки': 'Particles',
    'Налаштування': 'Settings',
    'налаштування': 'settings',
    'Клас': 'Class',
    'клас': 'class',
    'Відскок': 'Bounce',
    'відскок': 'bounce',
    'від країв': 'from edges',
    'Від країв': 'From edges',
    'Забезпечуємо': 'Ensure',
    'забезпечуємо': 'ensure',
    'що': 'that',
    'Що': 'That',
    'залишаються': 'stay',
    'Залишаються': 'Stay',
    'в межах': 'within bounds',
    'В межах': 'Within bounds',
    'Малюємо': 'Draw',
    'малюємо': 'draw',
    'лінії': 'lines',
    'Лінії': 'Lines',
    'між': 'between',
    'Між': 'Between',
    'близькими': 'close',
    'Близькими': 'Close',
    'parallax': 'parallax',
    'відео': 'video',
    'Відео': 'Video',
    'всіх': 'all',
    'Всіх': 'All',
    'accordion': 'accordion',
    'відгуків': 'testimonials',
    'Відгуків': 'Testimonials',
    'auto-resize': 'auto-resize',
    'textarea': 'textarea',
    'автоматичного': 'automatic',
    'Автоматичного': 'Automatic',
    'змінення': 'changing',
    'Змінення': 'Changing',
    'розміру': 'size',
    'Розміру': 'Size',
    'показу': 'show',
    'Показу': 'Show',
    'приховування': 'hide',
    'Приховування': 'Hide',
    'burger': 'burger',
    'активного': 'active',
    'Активного': 'Active',
    'nav link': 'nav link',
    'на скролі': 'on scroll',
    'На скролі': 'On scroll',
    'різних': 'different',
    'Різних': 'Different',
    'сторінок': 'pages',
    'Сторінок': 'Pages',
    'Замінюємо': 'Replace',
    'замінюємо': 'replace',
    'існуючу': 'existing',
    'Існуючу': 'Existing',
    'вставляємо нову': 'insert new',
    'Вставляємо нову': 'Insert new',
    'canvas': 'canvas',
    'Canvas': 'Canvas',
    'з': 'with',
    'З': 'With',
    'частинками': 'particles',
    'Частинками': 'Particles',
    'hero': 'hero',
    'Hero': 'Hero',
    'перевіряємо': 'check',
    'чи вже є': 'if already exists',
    'Чи вже є': 'If already exists',
    'Оновлюємо та': 'Update and',
    'оновлюємо та': 'update and',
    'малюємо': 'draw',
    'Малюємо': 'Draw',
    'Функція': 'Function',
    'функція': 'function',
    'анімації': 'animation',
    'Анімації': 'Animation',
    'Оновлюємо висоту': 'Update height',
    'оновлюємо висоту': 'update height',
    'Отримуємо': 'Get',
    'отримуємо': 'get',
    'Знаходимо': 'Find',
    'знаходимо': 'find',
    'Отримуємо слайди': 'Get slides',
    'отримуємо слайди': 'get slides',
    'Ініціалізуємо карусель': 'Initialize carousel',
    'ініціалізуємо карусель': 'initialize carousel',
    'Приховуємо кнопки': 'Hide buttons',
    'приховуємо кнопки': 'hide buttons',
    'Якщо карусель': 'If carousel',
    'якщо карусель': 'if carousel',
    'не може бути': "can't be",
    'Не може бути': "Can't be",
    'ініціалізована': 'initialized',
    'Ініціалізована': 'Initialized',
    'немає слайдів': "doesn't have slides",
    'Немає слайдів': "Doesn't have slides",
    'треку': 'track',
    'Треку': 'Track',
    'тощо': 'etc',
    'Тощо': 'Etc',
    'просто': 'just',
    'Просто': 'Just',
    'пропускаємо': 'skip',
    'Пропускаємо': 'Skip',
    'її': 'it',
    'Її': 'It',
    'Очищення': 'Cleanup',
    'очищення': 'cleanup',
    'всіх каруселей': 'all carousels',
    'Всіх каруселей': 'All carousels',
    'видалення слухачів': 'removal of listeners',
    'Видалення слухачів': 'Removal of listeners',
    'подій': 'events',
    'Подій': 'Events',
    'Корисно при': 'Useful when',
    'корисно при': 'useful when',
    'динамічному оновленні': 'dynamic update',
    'Динамічному оновленні': 'Dynamic update',
    'сторінки': 'page',
    'Сторінки': 'Page',
    'Отримати всі': 'Get all',
    'отримати всі': 'get all',
    'екземпляри каруселей': 'carousel instances',
    'Екземпляри каруселей': 'Carousel instances',
    'Корисно для': 'Useful for',
    'корисно для': 'useful for',
    'програмного керування': 'programmatic control',
    'Програмного керування': 'Programmatic control',
    'каруселями': 'carousels',
    'Каруселями': 'Carousels',
    'Компонент каруселі': 'Carousel component',
    'компонент каруселі': 'carousel component',
    'перевикористовуваний клас': 'reusable class',
    'Перевикористовуваний клас': 'Reusable class',
    'для роботи з каруселями': 'for working with carousels',
    'Для роботи з каруселями': 'For working with carousels',
    'Чи використовувати безкінечний цикл': 'Whether to use infinite loop',
    'чи використовувати безкінечний цикл': 'whether to use infinite loop',
    'Тривалість анімації переходу в мс': 'Animation transition duration in ms',
    'тривалість анімації переходу в мс': 'animation transition duration in ms',
    'Поріг для свайпу на мобільних пристроях': 'Swipe threshold for mobile devices',
    'поріг для свайпу на мобільних пристроях': 'swipe threshold for mobile devices',
    'Селектор для кнопки "Попереднє"': 'Selector for "Previous" button',
    'селектор для кнопки "Попереднє"': 'selector for "Previous" button',
    'Селектор для кнопки "Наступне"': 'Selector for "Next" button',
    'селектор для кнопки "Наступне"': 'selector for "Next" button',
    'Селектор для треку каруселі': 'Selector for carousel track',
    'селектор для треку каруселі': 'selector for carousel track',
    'Обробники подій для видалення': 'Event handlers for removal',
    'обробники подій для видалення': 'event handlers for removal',
    'Встановлюємо опції за замовчуванням': 'Set default options',
    'встановлюємо опції за замовчуванням': 'set default options',
    'Знаходимо елементи': 'Find elements',
    'знаходимо елементи': 'find elements',
    'Отримуємо слайди': 'Get slides',
    'отримуємо слайди': 'get slides',
    'Ініціалізуємо карусель': 'Initialize carousel',
    'ініціалізуємо карусель': 'initialize carousel',
    'Приховуємо кнопки, якщо є тільки 1 слайд': 'Hide buttons if only 1 slide',
    'приховуємо кнопки, якщо є тільки 1 слайд': 'hide buttons if only 1 slide',
    'Якщо тільки 1 слайд, не додаємо слухачі подій': "If only 1 slide, don't add event listeners",
    'якщо тільки 1 слайд, не додаємо слухачі подій': "if only 1 slide, don't add event listeners",
    'Налаштовуємо безкінечний цикл, якщо потрібно': 'Setup infinite loop if needed',
    'налаштовуємо безкінечний цикл, якщо потрібно': 'setup infinite loop if needed',
    'Встановлюємо початкову позицію': 'Set initial position',
    'встановлюємо початкову позицію': 'set initial position',
    'Додаємо слухачі подій': 'Add event listeners',
    'додаємо слухачі подій': 'add event listeners',
    'Оновлюємо при зміні розміру вікна': 'Update on window resize',
    'оновлюємо при зміні розміру вікна': 'update on window resize',
    'Захист від подвійного навішування': 'Protection from double binding',
    'захист від подвійного навішування': 'protection from double binding',
    'Закриваємо всі інші елементи': 'Close all other elements',
    'закриваємо всі інші елементи': 'close all other elements',
    'Перемикаємо поточний елемент': 'Toggle current element',
    'перемикаємо поточний елемент': 'toggle current element',
    'Визначення поточної сторінки за URL': 'Determine current page by URL',
    'визначення поточної сторінки за URL': 'determine current page by URL',
    'Ініціалізація Hero секції на поточній сторінці': 'Initialize Hero section on current page',
    'ініціалізація Hero секції на поточній сторінці': 'initialize Hero section on current page',
    'Перевіряємо, чи вже є hero секція': 'Check if hero section already exists',
    'перевіряємо, чи вже є hero секція': 'check if hero section already exists',
    'Якщо є, оновлюємо її': 'If exists, update it',
    'якщо є, оновлюємо її': 'if exists, update it',
    'Замінюємо існуючу hero': 'Replace existing hero',
    'замінюємо існуючу hero': 'replace existing hero',
    'Якщо немає, вставляємо нову': "If doesn't exist, insert new",
    'якщо немає, вставляємо нову': "if doesn't exist, insert new",
    'Ініціалізація Hero з кастомною конфігурацією': 'Initialize Hero with custom configuration',
    'ініціалізація Hero з кастомною конфігурацією': 'initialize Hero with custom configuration',
    'Модуль для динамічних ефектів фону': 'Module for dynamic background effects',
    'модуль для динамічних ефектів фону': 'module for dynamic background effects',
    'Ініціалізація анімованого градієнта для hero overlay': 'Initialize animated gradient for hero overlay',
    'ініціалізація анімованого градієнта для hero overlay': 'initialize animated gradient for hero overlay',
    'Працює тільки на головній сторінці, не на підсторінках': 'Works only on main page, not on subpages',
    'працює тільки на головній сторінці, не на підсторінках': 'works only on main page, not on subpages',
    'Функція збережена для майбутнього використання в інших секціях': 'Function saved for future use in other sections',
    'функція збережена для майбутнього використання в інших секціях': 'function saved for future use in other sections',
    'Не використовуємо анімацію на підсторінках': "Don't use animation on subpages",
    'не використовуємо анімацію на підсторінках': "don't use animation on subpages",
    'Створюємо анімований градієнт через CSS змінні': 'Create animated gradient via CSS variables',
    'створюємо анімований градієнт через CSS змінні': 'create animated gradient via CSS variables',
    'Анімація градієнта': 'Gradient animation',
    'анімація градієнта': 'gradient animation',
    'Перевіряємо, чи hero все ще існує і не став підсторінкою': 'Check if hero still exists and hasn\'t become subpage',
    'перевіряємо, чи hero все ще існує і не став підсторінкою': 'check if hero still exists and hasn\'t become subpage',
    'Створення canvas з частинками для hero секції': 'Create canvas with particles for hero section',
    'створення canvas з частинками для hero секції': 'create canvas with particles for hero section',
    'Працює тільки на головній сторінці, не на підсторінках': 'Works only on main page, not on subpages',
    'працює тільки на головній сторінці, не на підсторінках': 'works only on main page, not on subpages',
    'Не використовуємо частинки на підсторінках': "Don't use particles on subpages",
    'не використовуємо частинки на підсторінках': "don't use particles on subpages",
    'Перевіряємо, чи вже є canvas': 'Check if canvas already exists',
    'перевіряємо, чи вже є canvas': 'check if canvas already exists',
    'Налаштування canvas': 'Canvas settings',
    'налаштування canvas': 'canvas settings',
    'Клас частинки': 'Particle class',
    'клас частинки': 'particle class',
    'Відскок від країв': 'Bounce from edges',
    'відскок від країв': 'bounce from edges',
    'Забезпечуємо, що частинки залишаються в межах': 'Ensure particles stay within bounds',
    'забезпечуємо, що частинки залишаються в межах': 'ensure particles stay within bounds',
    'Створюємо масив частинок': 'Create particles array',
    'створюємо масив частинок': 'create particles array',
    'Функція анімації': 'Animation function',
    'функція анімації': 'animation function',
    'Оновлюємо та малюємо частинки': 'Update and draw particles',
    'оновлюємо та малюємо частинки': 'update and draw particles',
    'Малюємо лінії між близькими частинками': 'Draw lines between close particles',
    'малюємо лінії між близькими частинками': 'draw lines between close particles',
    'Ініціалізація parallax ефекту для hero відео': 'Initialize parallax effect for hero video',
    'ініціалізація parallax ефекту для hero відео': 'initialize parallax effect for hero video',
    'Ініціалізація всіх ефектів фону': 'Initialize all background effects',
    'ініціалізація всіх ефектів фону': 'initialize all background effects',
    'Ініціалізація каруселі відгуків': 'Initialize testimonials carousel',
    'ініціалізація каруселі відгуків': 'initialize testimonials carousel',
    'Ініціалізація FAQ accordion': 'Initialize FAQ accordion',
    'ініціалізація FAQ accordion': 'initialize FAQ accordion',
    'Ініціалізація автоматичного змінення розміру textarea': 'Initialize automatic textarea resize',
    'ініціалізація автоматичного змінення розміру textarea': 'initialize automatic textarea resize',
    'Ініціалізація автоматичного показу/приховування burger меню': 'Initialize automatic burger menu show/hide',
    'ініціалізація автоматичного показу/приховування burger меню': 'initialize automatic burger menu show/hide',
    'Ініціалізація плавної прокрутки навігації': 'Initialize smooth scroll navigation',
    'ініціалізація плавної прокрутки навігації': 'initialize smooth scroll navigation',
    'Ініціалізація активного nav link на скролі': 'Initialize active nav link on scroll',
    'ініціалізація активного nav link на скролі': 'initialize active nav link on scroll',
    'Ініціалізація мобільного меню': 'Initialize mobile menu',
    'ініціалізація мобільного меню': 'initialize mobile menu',
    'Ініціалізація ефекту скролу для header': 'Initialize scroll effect for header',
    'ініціалізація ефекту скролу для header': 'initialize scroll effect for header',
    'Ініціалізація затемнення services секції при скролі': 'Initialize services section darkening on scroll',
    'ініціалізація затемнення services секції при скролі': 'initialize services section darkening on scroll',
    'Ініціалізація всіх анімацій': 'Initialize all animations',
    'ініціалізація всіх анімацій': 'initialize all animations',
    'Ініціалізуємо AOS (Animate On Scroll)': 'Initialize AOS (Animate On Scroll)',
    'ініціалізуємо AOS (Animate On Scroll)': 'initialize AOS (Animate On Scroll)',
    'Анімація Header елементів при завантаженні': 'Header elements animation on load',
    'анімація Header елементів при завантаженні': 'header elements animation on load',
    'Спочатку ховаємо елементи': 'First hide elements',
    'спочатку ховаємо елементи': 'first hide elements',
    'Анімація logo (зліва)': 'Logo animation (from left)',
    'анімація logo (зліва)': 'logo animation (from left)',
    'Анімація navigation (зверху)': 'Navigation animation (from top)',
    'анімація navigation (зверху)': 'navigation animation (from top)',
    'Анімація nav links по черзі': 'Nav links animation one by one',
    'анімація nav links по черзі': 'nav links animation one by one',
    'Анімація actions (справа)': 'Actions animation (from right)',
    'анімація actions (справа)': 'actions animation (from right)',
    'Анімація Hero секції': 'Hero section animation',
    'анімація Hero секції': 'hero section animation',
    'Анімація project cards при hover': 'Project cards animation on hover',
    'анімація project cards при hover': 'project cards animation on hover',
    'Анімація кнопок форми при hover': 'Form buttons animation on hover',
    'анімація кнопок форми при hover': 'form buttons animation on hover',
    'Анімація services-hero cards при hover': 'Services-hero cards animation on hover',
    'анімація services-hero cards при hover': 'services-hero cards animation on hover',
    'Ініціалізація Footer секції на поточній сторінці': 'Initialize Footer section on current page',
    'ініціалізація Footer секції на поточній сторінці': 'initialize Footer section on current page',
    'Ініціалізація Footer з кастомною конфігурацією': 'Initialize Footer with custom configuration',
    'ініціалізація Footer з кастомною конфігурацією': 'initialize Footer with custom configuration',
    'Конфігурації Hero для різних сторінок': 'Hero configurations for different pages',
    'конфігурації Hero для різних сторінок': 'hero configurations for different pages',
    'Конфігурація Footer за замовчуванням': 'Default Footer configuration',
    'конфігурація Footer за замовчуванням': 'default Footer configuration',
    'Navigation модуль': 'Navigation module',
    'navigation модуль': 'navigation module',
    'smooth scroll': 'smooth scroll',
    'active nav link': 'active nav link',
    'auto burger menu': 'auto burger menu',
    'Header модуль': 'Header module',
    'header модуль': 'header module',
    'scroll effect': 'scroll effect',
    'та затемнення services': 'and services darkening',
    'Animations модуль': 'Animations module',
    'animations модуль': 'animations module',
    'AOS та Anime.js анімації': 'AOS and Anime.js animations',
    'aos та anime.js анімації': 'aos and anime.js animations',
    'Carousel модуль': 'Carousel module',
    'carousel модуль': 'carousel module',
    'проекти каруселі з infinite loop': 'projects carousel with infinite loop',
    'Проекти каруселі з infinite loop': 'Projects carousel with infinite loop',
    'Testimonials модуль': 'Testimonials module',
    'testimonials модуль': 'testimonials module',
    'карусель відгуків': 'testimonials carousel',
    'Карусель відгуків': 'Testimonials carousel',
    'FAQ модуль': 'FAQ module',
    'faq модуль': 'faq module',
    'Модуль для ініціалізації Hero секцій': 'Module for initializing Hero sections',
    'модуль для ініціалізації Hero секцій': 'module for initializing Hero sections',
    'Модуль для ініціалізації Footer секцій': 'Module for initializing Footer sections',
    'модуль для ініціалізації Footer секцій': 'module for initializing Footer sections',
    'Form модуль': 'Form module',
    'form модуль': 'form module',
    'Модуль для динамічних ефектів фону': 'Module for dynamic background effects',
    'модуль для динамічних ефектів фону': 'module for dynamic background effects',
    'Ініціалізація всіх модулів': 'Initialize all modules',
    'ініціалізація всіх модулів': 'initialize all modules',
    'Після збірки виправляємо шляхи в HTML файлах': 'After build fix paths in HTML files',
    'після збірки виправляємо шляхи в HTML файлах': 'after build fix paths in HTML files',
    'Додаємо base path до відносних шляхів у script та link тегах': 'Add base path to relative paths in script and link tags',
    'додаємо base path до відносних шляхів у script та link тегах': 'add base path to relative paths in script and link tags',
    'Пропускаємо шляхи, які вже мають base path або абсолютні': 'Skip paths that already have base path or absolute',
    'пропускаємо шляхи, які вже мають base path або абсолютні': 'skip paths that already have base path or absolute',
    'Створюємо .nojekyll файл для GitHub Pages': 'Create .nojekyll file for GitHub Pages',
    'створюємо .nojekyll файл для GitHub Pages': 'create .nojekyll file for GitHub Pages',
    'Новий проект сайту Style Homes, створюється з нуля (ну майже)': 'New Style Homes website project, created from scratch (well almost)',
    'новий проект сайту Style Homes, створюється з нуля (ну майже)': 'new Style Homes website project, created from scratch (well almost)',
}

# File extensions to process
EXTENSIONS = {'.ts', '.js', '.css', '.html', '.java', '.yml', '.yaml', '.json'}

# Directories to exclude
EXCLUDE_DIRS = {'node_modules', 'dist', 'target', '.git', '__pycache__', 'backend/target'}

def should_exclude(filepath):
    """Check if file should be excluded"""
    parts = Path(filepath).parts
    for exclude_dir in EXCLUDE_DIRS:
        if exclude_dir in parts:
            return True
    return False

def replace_cyrillic_in_file(filepath):
    """Replace Cyrillic comments with English in a file"""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        
        original_content = content
        
        # Replace translations
        for ukr, eng in TRANSLATIONS.items():
            content = content.replace(ukr, eng)
        
        # If content changed, write it back
        if content != original_content:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
            return True
        return False
    except Exception as e:
        print(f"Error processing {filepath}: {e}")
        return False

def main():
    """Main function"""
    print("Replacing Cyrillic comments with English...")
    print()
    
    base_path = Path('.')
    changed_files = []
    
    for filepath in base_path.rglob('*'):
        if filepath.is_file() and filepath.suffix in EXTENSIONS:
            if not should_exclude(filepath):
                if replace_cyrillic_in_file(filepath):
                    changed_files.append(str(filepath))
    
    if changed_files:
        print(f"Updated {len(changed_files)} files:")
        for file in changed_files:
            print(f"  - {file}")
    else:
        print("No files were changed.")
    
    return changed_files

if __name__ == '__main__':
    main()
