ALTER TABLE consultations ALTER COLUMN last_name TYPE VARCHAR(100);
ALTER TABLE consultations ALTER COLUMN last_name DROP NOT NULL;
ALTER TABLE consultations ALTER COLUMN phone TYPE VARCHAR(20);
ALTER TABLE consultations ALTER COLUMN phone DROP NOT NULL;
